# Generated by Django 4.2.5 on 2023-10-20 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager_app", "0003_department_department_description_stream"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
    ]
