# Generated by Django 4.2.5 on 2023-10-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager_app", "0004_alter_department_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identification",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="none", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="none", max_length=32),
            preserve_default=False,
        ),
    ]
